INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('IPHONE 20', 555888);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('PIXEL', 15000);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('MacBook Pro, 1gb RAM, 1GHZ, 13inches', 999999999);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Huawei TotallyNotACloneOfIphone', 2000);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('XIOMI LAPTOP', 15999);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('YANDEX STATION', 20999);
INSERT INTO PRODUCTS (NAME, PRICE) VALUES ('Sbre station', 10888);